---
- name: Backup install packages
  apt:
    name: "{{ backup__default_packages }}"
    update_cache: yes
    state: present
  when:
    - backup__install
    - not backup__time_machine

- name: Create backup directory
  file:
    dest: "{{ backup__conf.local_dir }}"
    state: directory
    mode: 0700
  when:
    - backup__install
    - not backup__time_machine

- name: Create backup default parms file
  template:
    src: default_backup
    dest: "/etc/default/backup"
    mode: 0660
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup log rotate file
  template:
    src: logfile
    dest: "/etc/logrotate.d/backup"
    mode: 0664
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup_mysql file
  template:
    src: backup_mysql
    dest: "/usr/local/bin/backup_mysql"
    mode: 0770
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - backup__mysql
    - not backup__time_machine

- name: Create backup_mysql cron
  cron:
    name: "Backup MySQL"
    cron_file: backup_mysql
    state: present
    hour: "3"
    minute: "0"
    user: root
    job: /usr/local/bin/backup_mysql
  when:
    - backup__install
    - backup__configure
    - backup__mysql
    - not backup__time_machine

- name: Create backup_cleaner file
  template:
    src: backup_cleaner
    dest: "/usr/local/bin/backup_cleaner"
    mode: 0770
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup_cleaner cron
  cron:
    name: "Backup cleaner"
    cron_file: backup_cleaner
    state: present
    hour: "{{ backup__cleaner_hour }}"
    minute: "{{ backup__cleaner_min }}"
    user: root
    job: /usr/local/bin/backup_cleaner
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup_zones file
  template:
    src: backup_zones
    dest: "/usr/local/bin/backup_zones"
    mode: 0770
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup_zones cron
  cron:
    name: "Backup zones"
    cron_file: backup_zones
    state: present
    hour: "3"
    minute: "0"
    user: root
    job: /usr/local/bin/backup_zones
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup_users file
  template:
    src: backup_users
    dest: "/usr/local/bin/backup_users"
    mode: 0770
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup_users cron
  cron:
    name: "Backup users"
    cron_file: backup_users
    state: present
    hour: "4"
    minute: "0"
    user: root
    job: /usr/local/bin/backup_users
  when:
    - backup__install
    - backup__configure
    - not backup__time_machine

- name: Create backup_mirror file
  template:
    src: backup_mirror
    dest: "/usr/local/bin/backup_mirror"
    mode: 0770
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - backup__mirror

- name: Create Return2ThePast file
  template:
    src: Return2ThePast
    dest: "/usr/local/bin/Return2ThePast"
    mode: 0770
    owner: root
    group: root
  when:
    - backup__install
    - backup__configure
    - backup__time_machine

- name: Create backup_mirror cron
  cron:
    name: "Backup mirror"
    cron_file: backup_mirror
    state: present
    hour: "{{ backup__mirror_hour }}"
    minute: "{{ backup__mirror_min }}"
    user: root
    job: /usr/local/bin/backup_mirror
  when:
    - backup__install
    - backup__configure
    - backup__mirror
    - not backup__time_machine
