#!/bin/bash
# Databases backup

# Quelques valeurs par défaut
BACKUP_DIR="{{ backup__conf.local_dir }}"
BACKUP_CONF_FILE="{{ backup__conf.local_conf }}"
BACKUP_CYPHER="{{ backup__conf.file_cypher }}"

# Si un fichier de paramètres existe, alors on le source
[ -e "$BACKUP_CONF_FILE" ] && . "$BACKUP_CONF_FILE"

LOGFILE={{ backup__conf.logfile }}

BACKUP_ON=${BACKUP_DIR}/$(date +%Y-%m-%d)-mysql
YESTERDAY_BACKUP_ON=${BACKUP_DIR}/$(date -d "yesterday" +%Y-%m-%d)-mysql

MYSQLDUMP=/usr/bin/mysqldump
MYSQL=/usr/bin/mysql

DATABASES=$($MYSQL --user=root -r -B -e "show databases"|tail -n +2)

for dbase in $DATABASES
do
    [[ "$dbase" =~ .*_schema ]] && continue
    if [ "$dbase" == "mysql" ]
    then
	$MYSQLDUMP --opt --events --add-drop-database -r ${BACKUP_ON}-${dbase}.sql $dbase >> $LOGFILE 2>&1
    else
	$MYSQLDUMP --opt --add-drop-database -r ${BACKUP_ON}-${dbase}.sql $dbase >> $LOGFILE 2>&1
    fi
    gzip ${BACKUP_ON}-${dbase}.sql
    # rm -f ${BACKUP_ON}-${dbase}.sql

    # Ensuite, on va chiffrer le résultat
    gpg --batch --output ${BACKUP_ON}-${dbase}.sql.gz.gpg --passphrase "$BACKUP_CYPHER" --symmetric ${BACKUP_ON}-${dbase}.sql.gz
    # Et supprimer la version non chiffrée
    rm -f ${BACKUP_ON}-${dbase}.sql.gz

    # Puis on vérifie qu'il y a bien eu des changements...
    # Le fichier est-il présent?
    [ ! -f ${YESTERDAY_BACKUP_ON}-${dbase}.sql.gz.gpg ] && continue
    YSum=$(md5sum ${YESTERDAY_BACKUP_ON}-${dbase}.sql.gz.gpg|sed -e 's/ .*//')
    Sum=$(md5sum ${BACKUP_ON}-${dbase}.sql.gz.gpg|sed -e 's/ .*//')
    # Et si c'est pareil, alors on efface hier
    [ "$YSum" = "$Sum" ] && rm -f ${YESTERDAY_BACKUP_ON}-${dbase}.sql.gz.gpg
done
