#!/bin/bash
# Nettoyage des backups
#

# Quelques valeurs par défaut
# La syntaxe de l'âge est: "<subdir>:<age>[;<subdir>:<age>]*"
# où subdir est la partie du nom du fichier qui en décrit le type (mysql, etc, datas, users, ..)
# et age = nD | nW | nM | nY
# Pour les jours, les semaines, les mois et les années

# Quelques valeurs par défaut
BACKUP_DIR="{{ backup__conf.local_dir }}"
BACKUP_AGE="*:4W"
BACKUP_CONF_FILE="{{ backup__conf.local_conf }}"

# Si un fichier de paramètres existe, alors on le source
[ -e "$BACKUP_CONF_FILE" ] && . "$BACKUP_CONF_FILE"

for group in $(echo $BACKUP_AGE|sed -e 's/\;/ /g')
do
  # On extrait le répertoire et l'âge
  AGE=${group/*:/}
  REP=${group/:*/}
  AGE=$(echo $AGE|sed -e 's/D/ day/;s/W/ week/;s/M/ month/;s/Y/ year/')
  # On calcule la date de référence
  DRef=$(date -d "${AGE} ago" +%Y-%m-%d)
  # Et si il y a un paramètre, alors c'est une date de réf.
  [ -z "$1" ] || DRef=$1

  TMPREF=$(mktemp --tmpdir -q "reffileXXXXX")
  
  # Create file date reference
  touch -d $DRef ${TMPREF}

  for f in $(find ${BACKUP_DIR} ! -newer ${TMPREF} ! -name "manual-*" -name "*-${REP}-*")
  do
      rm -f "$f"
  done
  rm -f ${TMPREF}
done
