#!/bin/bash
# Return2ThePast
#

# Quelques valeurs par défaut
BACKUP_DIR="{{ backup__conf.local_dir }}"
BACKUP_CONF_FILE="{{ backup__conf.local_conf }}"
BACKUP_CYPHER="{{ backup__conf.file_cypher }}"

# Si un fichier de paramètres existe, alors on le source
[ -e "$BACKUP_CONF_FILE" ] && . "$BACKUP_CONF_FILE"

R2TP_LABEL="R2TP"
R2TP_DISK="/media/francois/"${R2TP_LABEL}
R2TP_DIR="/media/francois/"${R2TP_LABEL}"/Backup"

RDIFF_OPTIONS="--verbosity 2 --tempdir ${R2TP_DISK}"
RDIFF_BACKUP_OPTIONS="--exclude **/.cache --exclude-sockets --exclude-device-files --exclude-fifos"

if [ $# -lt 1 ]
then
cat >&2 <<EOF
Usage: Return2ThePast <command> [file ...]

commands are:
  backup [file ...]
  restore [file ...]
  sysbackup (root only)
  sysrestore (root only)
  check [file ...]
  clean [date ...] (ex: 3Y = 3 years, 10M = Ten month
EOF
  exit
fi

# On vérifie que le disque est bien là
if (mount|grep -q ${R2TP_DISK})
then
    :
else
    echo "Return2ThePast disk is not present" >&2
    exit
fi

#
# Les commandes:
#   backup [file ...]
#   restore [file ...]
#   sysbackup (root only)
#   sysrestore (root only)
#   check [file ...]
#   clean [date ...]
#

case $1 in
  sysbackup)
    dpkg --get-selections > /etc/package-list
    for b in $BACKUP_ZONES
    do
	mkdir -p ${R2TP_DIR}$b
	echo -n "Backup of $b ..."
	rdiff-backup $RDIFF_OPTIONS backup $RDIFF_BACKUP_OPTIONS $b ${R2TP_DIR}$b
	echo "Done"
    done
    ;;
  clean)
    for b in $BACKUP_ZONES
    do
	# Find the backup duration
	for group in $(echo $BACKUP_AGE|sed -e 's/\;/ /g')
	do
	    # On extrait le répertoire et l'âge
	    AGE=${group/*:/}
	    REP=${group/:*/}
	    if [[ "$REP" == "*" ]]
	    then
		DURATION=$AGE
	    fi
	    if [[ "$b" =~ "$REP" ]]
	    then
		DURATION=$AGE
	    fi
	done
	[ -z "$DURATION" ] && DURATION="2Y"
	rdiff-backup --force remove increments --older-than $DURATION ${R2TP_DIR}$b
    done
    ;;
  backup|*restore)
    echo "Don't know how to backup/restore/sysrestore files, now" >&2
    ;;
  check)
    echo "Don't know how to check files, now" >&2
    ;;
  infos)
    shift
    for file in $@
    do
	echo "Checking file " $file >> /tmp/R2TP.log
	echo rdiff-backup $RDIFF_OPTIONS --compare $file ${R2TP_DIR}$file >> /tmp/R2TP.log
    done
    ;;
esac

exit 0

